/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    EmbeddedBrowser: typeof import('./src/components/EmbeddedBrowser.vue')['default']
    QueryStatsToast: typeof import('./src/components/QueryStatsToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerTip: typeof import('./src/components/ServerTip.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    WebsitePreview: typeof import('./src/components/WebsitePreview.vue')['default']
  }
}
