import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import { createI18n } from "vue-i18n";
import "./style.css";

const messages = {
  "zh-CN": {
    nav: {
      home: "首页",
      categories: "分类",
      tags: "标签",
      portfolios: "作品",
      friendLinks: "友链",
      subscribe: "订阅",
      goods: "好物",
      about: "关于",
    },
    search: {
      placeholder: "搜索文章...",
      action: "搜索",
    },
    language: {
      toggle: "切换语言",
      zh: "中文",
      en: "English",
    },
    about: {
      intro: "欢迎来到 ApexBlog！这里是我分享技术心得、记录学习历程的地方。",
      tagline: "一个专注于技术分享的个人博客",
      profileTitle: "个人简介",
      profileText:
        "独立开发者｜Rust 爱好者｜把你的独立作品展示给全世界。",
      learnMore: "了解更多",
      contactTitle: "联系方式",
      email: "邮箱",
    },
    footer: {
      nonAi: "非 AI 生成",
      nonAiTitle: "非AI生成",
      humanWritten: "真人撰写",
      nonAiDesc: "除特别注明的引用内容外，本站文章没有任何一句话由 AI 生成。",
      learnMore: "了解更多",
    },
    home: {
      bannerPrefix:
        "我的新产品 soloforge 已上线，让世界看见你的独立产品，访问：",
    },
  },
  en: {
    nav: {
      home: "Home",
      categories: "Categories",
      tags: "Tags",
      portfolios: "Portfolio",
      friendLinks: "Links",
      subscribe: "Subscribe",
      goods: "Goods",
      about: "About",
    },
    search: {
      placeholder: "Search articles...",
      action: "Search",
    },
    language: {
      toggle: "Switch language",
      zh: "中文",
      en: "English",
    },
    about: {
      intro:
        "Welcome to ApexBlog! This is where I share notes and learnings.",
      tagline: "A personal blog for sharing and notes.",
      profileTitle: "Profile",
      profileText:
        "Indie dev | Rust fan | Showcase your indie creation to the world.",
      learnMore: "Learn more",
      contactTitle: "Contact",
      email: "Email",
    },
    footer: {
      nonAi: "Human-written",
      nonAiTitle: "Not AI-generated",
      humanWritten: "Human-written",
      nonAiDesc:
        "Except where explicitly cited, no sentence on this site is generated by AI.",
      learnMore: "Learn more",
    },
    home: {
      bannerPrefix:
        "My new product SoloForge is live — let the world see your indie product. Visit:",
    },
  },
};

const resolveInitialLocale = () => {
  const saved = localStorage.getItem("ornata_locale");
  if (saved && (saved === "zh-CN" || saved === "en")) return saved;
  const lang = navigator.language || "";
  return lang.toLowerCase().startsWith("zh") ? "zh-CN" : "en";
};

const i18n = createI18n({
  legacy: false,
  locale: resolveInitialLocale(),
  fallbackLocale: "zh-CN",
  messages,
});

const app = createApp(App);

// ????????
app.config.errorHandler = (err, _vm, info) => {
  console.error("Vue??????:", err, info);
};

// ???��?????Promise??????
window.addEventListener("unhandledrejection", (event) => {
  console.error("��?????Promise????:", event.reason);
  event.preventDefault();
});

app.use(router);
app.use(i18n);
app.mount("#app");
